language: clojure
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  # - lein source-deps
  - $TEST_CMD
env:
  # - TEST_CMD="lein with-profile +1.5,+test-clj test"
  # - TEST_CMD="lein with-profile +1.6,+test-clj test"
  - TEST_CMD="lein with-profile +test test"
  - TEST_CMD="lein with-profile +test-cljs doo phantom test once"

  # - TEST_CMD="lein with-profile +1.6,+test-cljs test"
  # - TEST_CMD="lein with-profile +1.7,+test-cljs test"
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
matrix:
  exclude:
    # - env: TEST_CMD="lein with-profile +1.6 test"
    #   jdk: openjdk6
    - env: TEST_CMD="lein with-profile +test test"
      jdk: openjdk6
    - env: TEST_CMD="lein with-profile +test-cljs doo phantom test once"
      jdk: openjdk6
  include:
    - env: TEST_CMD="lein with-profile +test,+coveralls coveralls"
      jdk: oraclejdk8
    - env: TEST_CMD="lein with-profile +test,+eastwood eastwood"
      jdk: oraclejdk8
    - env: TEST_CMD="lein with-profile +test,+cljfmt cljfmt check"
      jdk: oraclejdk8

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
